### ISSUE TITLE
baseUrl aund Deployment Ordner

### ISSUE THREAD

**Issue by gisma** [IvoJJ/GIS-2021-22-Jung#1]
@IvoJJ schön zumindest der NAchweis dass es gelingen kann ;-)

Falls die Seite von GitHub ausgeliefert  werden soll muss sie anders hochgeladen werden. GitHub kann nur entweder das Wurzelverzeich oder das Verzeichnis `/docs`  einbinden. dazu muss in der `config.yaml` die `baseUrl` und das `publishDir` Verzeichnis angegeben werden:
```yaml
baseURL: 'https://ivojj.github.io/GIS-2021-22-Jung/'
publishDir: docs
```
Dazu muss das public Verzeichnis manuell gelöscht werden und die seiten dann wie immer mit `blogdown::build_site(build_rmd = T) ` neu kompiliert werden.

**Comment by IvoJJ** [comment]
Hallo Chris, vielen Dank. Ich Blick noch nicht ganz durch aber das sind
wohl alles Probleme die man beheben kann. Schreibe ich das

publishDir: docs

einfach in die yaml Datei?
Und danach rebuilde ich einfach die Seite in R, commite und pushe dann und
dann kann github pages das kompilieren?

Wegen der uploads der assignments... Sollen die die dann einfach als rmd
als Blog posts in die Website einbinden oder auch nach in dasselbe repo
(oder ein separates? Bin mir nicht sicher, ob es easy geht noch assignment
Ordner in das repo mit einzubinden ohne mit der website zu conflicted)?

Vielen Dank und viele Grüße
 Ivo

Chris Reudenbach ***@***.***> schrieb am Di., 23. Nov. 2021,
19:47:

**Comment by gisma** [comment]
### fixen der einträge
1. copy paste in die ersten beiden Zeilen.
2. löschen des `public` Ordner löscht alte webseite 
3.  kompilieren erzeugt unter `docs` neue seite
4. committen der änderungen
5. pushen
6. unter github settings pages noch die seiten auf docs einstellen 
7. und ca 5 minuten warten

### assignments 
einfach im blog schreiben und wenn fertig genauso comiten und pushen wie beschrieben

**Comment by IvoJJ** [comment]
Ich probiere noch etwas rum, deine Instruktionen sind ja recht klar mit den Schritten. Falls doch melde ich mich hier nochmal!

**Comment by IvoJJ** [comment]
Okay, hab die Steps jetzt so abgewickelt. Die erstellte Website ist aber immernoch die meiner alten readme.md file wieso auch immer...

**Comment by gisma** [comment]
Evtl. ist es sinnvoll das teil nochmal neu aufzusetzen. Ich habe noch einige einstellunge verändert. Ausserdem überlege ich mir wie am einfachsten neue templates eingespielt werden können. Natürlich per github aber da geht nach der gestrigen Sitzung zu Urteilen leide r nicht soviel wie ich gerne hätte.

**Comment by IvoJJ** [comment]
@gisma meinst du mit neu aufsetzen jetzt nur mein repo + website? Ich hab bisher noch nicht versucht Inhalte hinzuzufügen, weil keine Zeit. Hoffentlich komme ich die Tage dazu. 

Falls eher generell gemeint: Ich denke das das an sich nicht verkehrt ist und du hast auch zu 100% recht damit, dass es in der Wissenschaft viel darauf ankommt eigenständig zu arbeiten (und zu denken :)). Die Problematik liegt gerade glaube ich eher in der Gesamtsituation. Du musst bedenken, es gibt Neuzugänge die bisher noch gar nichts mit R oder Git(Hub) am Hut hatten und für die das ganze ein komplett neuer Kosmos ist. Das die Coronasituation gerade auch eine beschissene Tendenz zeigt trägt auch noch zu dem Problem dabei. Ich denke die ganze Kost wäre leichter zu verdauen, wenn der Kurs zu 100% in Präsenz wäre (was leider nicht zwingend möglich ist gerade; ich war diese Woche z.B. nicht in Präsenz da, weil eine Person in meinem Umfeld positiv auf Corona getestet wurde und ich daher bisschen auf Kontaktvermeidung geachtet habe). Jedenfalls ist der Stoff glaube ich leichter zu vermitteln wenn man direkt von Person zu Person Rückfragen stellen kann und direkte Antworten/Feedback bekommt. 
Persönlich finde ich die Möglichkeiten & Materie ziemlich spannend; ich denke aber ein paar genauere Arbeitsanweisung bzw. Follow-Along "Tutorials" (wie z.B. mit der Einführung in Lidar: https://gisma-courses.github.io/gi-modules/post/2021-11-16-getting-startet-with-lidar/), welche direkt im Kurs behandelt werden sind eine sinnvolle Ergänzung und würden vielen Leuten helfen für sich selbst etwas Struktur in den Kurs zu bringen  (weil die Fülle an Content und Informationen ist einfach enorm).

Vielen Dank für die Hilfe!

**Comment by gisma** [comment]
@IvoJJ  merci für das feedback 
* zum Inhalt  ja klar ist da noch nichts drin eben drum wäre es sinnvoll das nochmal neu aufzusetzen. 
* zum Kurs 
wie in der email geschrieben bin ich maximal darauf bedacht flexibel alles zu ermöglichen was geht. Nur was nicht geht ist still zu sitzen und dann nichts zu tun. die  follow-alongs sind ja da und werden auch weiterhin da sein dürfen aber nicht alles abdecken weil who follows never leads... und genau das sollt ihr alle mal tun. Mir ist bewusst das wir  einiges verlangen und ich biete jede mir mögliche Hilfe an. Aber ich erwarte auch eine entsprechende Klarheit auf Studierendenseite. Und in einer Präsenzveranstaltung von nicht Anwesenden aufgefordert zu werden bitte eine Präsenzveranstaltung anzubieten ist schon ein bisschen "seltsam"...

**Comment by IvoJJ** [comment]
@gisma War nicht so gemeint, das ich eine Präsenzveranstaltung fordere; ich kann da nur für mich sprechen.. wenn die Umstände es zulassen komme ich in Präsenz (was diese Woche leider nicht der Fall war). Es war eher so gemeint, das ein Teil der Verwirrung auf den hohen Onlineanteil zurückzuführen ist; ist aber auch nur meine Vermutung - ich denke deine Forderung nach Kamera + Mikrofon sind jedenfalls sinnvoll.

**Comment by IvoJJ** [comment]
@gisma mit neu aufsetzen meinst du die index.rmd file bearbeiten im docs folder, oder? Also den beispielcontent einfach durch "meinen" content ersetzten und neu knittern + compilen + comitten & pushen.

**Comment by gisma** [comment]
da es nicht upstream an das template repo angebunden ist müsste dein  repo nochmal gelöscht und neu aufgesetzt werden  Ist die einfachere variante, da noch nichts an inhalten drin ist

**Comment by IvoJJ** [comment]
Können wir uns das morgen nochmal gemeinsam nach geoAI angucken?

**Comment by gisma** [comment]
@IvoJJ  sorry für die etwas anmaßende Bastelei, aber ich musste die Vorlage reparieren und bevor ihr alles neu einrichten müsst oder ich einen Pull Request mache, dachte ich, es wäre besser so. 
zumindest sollte es jetzt funktionieren. ich schließe den issue mal . falls noch was klemmt kannst du den ja nochmal öffnen.

**Comment by IvoJJ** [comment]
@gisma Hallo, vielen dank dafür, wäre cool wenn du mir vllt noch eine Erklärung dalassen könntest, an was du rumgedoktert hast (weiß nicht ob ich alles aus den commits richtig mitnehme). Bin erst seit gestern wieder von den toten auferstanden... :I

**Comment by gisma** [comment]
kompliziert aber kann ich machen. Im Prinzip habe ich einen bug im Template bereiningt. Es fehlte an einer Stelle der Eintrag des repo-namens. Ich habe das mit einem Update auf das template jetzt hoffentlich für alle gerichtet.
